FROM python:3.10

RUN adduser --disabled-password --gecos '' pypad

WORKDIR /home/pypad

ENV VENV=/home/pypad/venv

RUN python3 -m venv $VENV

ENV PATH="$VENV/bin:$PATH"

WORKDIR /home/pypad/code

COPY ./app/dist ./app/dist

COPY ./server/src/ ./server/src/
COPY ./server/setup.py ./server/requirements.txt ./server/

RUN python3 -m pip install --upgrade pip -e ./server --no-cache-dir

USER pypad

CMD ["python3", "-m", "pypad"]
